//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Application
{
    //public Application()
    //{
    //    this.Memberships = new HashSet<Membership>();   //initialize new instance oof each tble in the app constructor
    //    this.Roles = new HashSet<Role>();
    //    this.Users = new HashSet<User>();
    //}

    public string ApplicationName { get; set; }
    public System.Guid ApplicationId { get; set; }
    public string Description { get; set; }

    public virtual ICollection<Membership> Memberships { get; set; }
    public virtual ICollection<Role> Roles { get; set; }
    public virtual ICollection<User> Users { get; set; }
}

public partial class Membership
{
    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string Password { get; set; }
    public int PasswordFormat { get; set; }
    public string PasswordSalt { get; set; }
    public string Email { get; set; }
    public string PasswordQuestion { get; set; }
    public string PasswordAnswer { get; set; }
    public bool IsApproved { get; set; }
    public bool IsLockedOut { get; set; }
    public System.DateTime CreateDate { get; set; }
    public System.DateTime LastLoginDate { get; set; }
    public System.DateTime LastPasswordChangedDate { get; set; }
    public System.DateTime LastLockoutDate { get; set; }
    public int FailedPasswordAttemptCount { get; set; }
    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
    public int FailedPasswordAnswerAttemptCount { get; set; }
    public System.DateTime FailedPasswordAnswerAttemptWindowsStart { get; set; }
    public string Comment { get; set; }

    public virtual Application Application { get; set; }
    public virtual User User { get; set; }
}

public partial class Profile
{
    public System.Guid UserId { get; set; }
    public string PropertyNames { get; set; }
    public string PropertyValueStrings { get; set; }
    public byte[] PropertyValueBinary { get; set; }
    public System.DateTime LastUpdatedDate { get; set; }

    public virtual User User { get; set; }
}

public partial class Role
{
    public Role()
    {
        //this.Roles = new HashSet<Role>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid RoleId { get; set; }
    public string RoleName { get; set; }
    public string Description { get; set; }

    public virtual Application Application { get; set; }
    public virtual ICollection<User> Users { get; set; }
}

public partial class Table
{
    public int Id { get; set; }
    public string vdfsdf { get; set; }
    public string sdfdsfs { get; set; }
}

public partial class User
{
    public User()
    {
        this.Roles = new HashSet<Role>();
    }

    public System.Guid ApplicationId { get; set; }
    public System.Guid UserId { get; set; }
    public string UserName { get; set; }
    public bool IsAnonymous { get; set; }
    public System.DateTime LastActivityDate { get; set; }

    public virtual Application Application { get; set; }
    public virtual Membership Membership { get; set; }
    public virtual Profile Profile { get; set; }
    public virtual ICollection<Role> Roles { get; set; }
}

public partial class UsersOpenAuthAccount
{
    public string ApplicationName { get; set; }
    public string ProviderName { get; set; }
    public string ProviderUserId { get; set; }
    public string ProviderUserName { get; set; }
    public string MembershipUserName { get; set; }
    public Nullable<System.DateTime> LastUsedUtc { get; set; }

    public virtual UsersOpenAuthData UsersOpenAuthData { get; set; }
}

public partial class UsersOpenAuthData
{
    public UsersOpenAuthData()
    {
        this.UsersOpenAuthAccounts = new HashSet<UsersOpenAuthAccount>();
    }

    public string ApplicationName { get; set; }
    public string MembershipUserName { get; set; }
    public bool HasLocalPassword { get; set; }

    public virtual ICollection<UsersOpenAuthAccount> UsersOpenAuthAccounts { get; set; }
}
